.TH DEFAULTWORLDMAP 1 2025-Mar "" "get default map image for create a new world"
.SH NAME
defaultWorldMap \- defaultWorldMap()
.SH SYNOPSIS
\fIdefaultWorldMap()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.defaultWorldMap at map.R:line 3
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
