.\" man page create by R# package system.
.TH ERA 1 2000-Jan "evolve" "evolve"
.SH NAME
evolve \- run the simulation
.SH SYNOPSIS
\fIevolve(\fBworld\fR as <generic> GeographyPlate, 
\fBfile\fR as any, 
\fBtime\fR as integer = 1000, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run the simulation
.PP
.SH OPTIONS
.PP
\fBworld\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- 
 the result save file
. 
.PP
.PP
\fBtime\fB \fR\- -. 
.PP
.SH SEE ALSO
Era
.SH FILES
.PP
Evolution.dll
.PP
