.\" man page create by R# package system.
.TH ERA 1 2000-Jan "world" "world"
.SH NAME
world \- 
.SH SYNOPSIS
\fIworld(\fBsize\fR as any = [10,10,3], 
\fBreproductive_isolation\fR as double = 0.9, 
\fBreproduce_rate\fR as double = 0.5, 
\fBdna_size\fR as integer = 5, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Era
.SH FILES
.PP
Evolution.dll
.PP
