.\" man page create by R# package system.
.TH ERA 1 2000-Jan "world" "world"
.SH NAME
world \- create a new world
.SH SYNOPSIS
\fIworld(\fBmap\fR as <generic> Image, 
\fBheight\fR as integer = 3, 
\fBreproductive_isolation\fR as double = 0.9, 
\fBreproduce_rate\fR as double = 0.5, 
\fBdna_size\fR as integer = 6, 
\fBnatural_death\fR as integer = 50, 
\fBsexual_maturity\fR as integer = 3, 
\fBpredation_diff\fR as integer = 2, 
\fBwater_color\fR as string = "#0026ff", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a new world
.PP
.SH OPTIONS
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Era
.SH FILES
.PP
Evolution.dll
.PP
