.\" man page create by R# package system.
.TH ANALYSIS 1 2000-Jan "creatures" "creatures"
.SH NAME
creatures \- get all creatures from the simulation result
.SH SYNOPSIS
\fIcreatures(\fBfile\fR as <generic> DataReader);\fR
.SH DESCRIPTION
.PP
get all creatures from the simulation result
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
Analysis
.SH FILES
.PP
Evolution.dll
.PP
